# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SCCycleScrollView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher', '~> 3.10.1'
  # Pods for SCCycleScrollView

  target 'SCCycleScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SCCycleScrollViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
